version: '3'
tasks:
  install:
    desc: 安装依赖
    cmds:
      - pip install poetry
      - poetry install
  start:
    desc: run 
    cmds:
      - cmd /c "set PYTHONPATH=D:\50.code\35.git78py\trade78\src && poetry run python -m src.main --config config.ini"
  dev:
    desc: run 
    cmds:
      - cmd /c "set PYTHONPATH=D:\50.code\35.git78py\trade78\src && poetry run python -m src.main "
  dockerall:
    desc: 构建并推送Docker镜像
    cmds:
      - bash ./hooks/dockerall.sh
  docker:
    desc: 构建并推送Docker镜像
    cmds:
      - bash ./hooks/dockercopy.sh