version: '3'
tasks:
  install:
    desc: 安装依赖
    cmds:
      - pip install poetry
      - poetry install
      - poetry run python -m src.main --use_kafka_log false
  start:
    desc: run 
    cmds:
      - poetry run python -m src.main --use_kafka_log false
  dev:
    desc: run 
    cmds:
      - poetry run python -m src.main --use_kafka_log true
  dockerall:
    desc: 构建并推送Docker镜像
    cmds:
      - bash ./hooks/dockerall.sh
  docker:
    desc: 构建并推送Docker镜像
    cmds:
      - bash ./hooks/dockercopy.sh
  
