apiVersion: batch/v1
kind: CronJob
metadata:
  name: stockoptimizer-job
spec:
  schedule: "*/10 9-15 * * *"  # 周一到周五每天 17:00 到 23:59 每 10 分钟执行一次
  successfulJobsHistoryLimit: 1  # 保留最近一次成功的Job和Pod
  failedJobsHistoryLimit: 1  # 保留最近一次失败的Job和Pod
  concurrencyPolicy: Forbid  # 确保前一个任务完成之前不会启动新的任务
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: stockoptimizer
        spec:
          imagePullSecrets:
            - name: my-registry-secret
          containers:
          - name: stockoptimizer
            image: crpi-3zr415nakxg4qr8l.cn-hangzhou.personal.cr.aliyuncs.com/7788soft/trade78:latest
            imagePullPolicy: Always  # 强制拉取最新镜像
            env:
            - name: TZ
              value: "Asia/Shanghai"  # 设置容器时区为北京时间
            - name: APP_ENV
              value: "production"  # 切换为生产环境
            - name: APP_MODE
              value: "optimizer"  # 控制模式
            - name: sid
              value: "15d647fd-946d-93f6-2413-1a704fd65816"
            - name: uname
              value: "systestvps"
            - name: BOOTSTRAP_SERVERS
              value: "kafka.default.svc.cluster.local:9092"
            - name: USE_KAFKA_LOG
              value: "true"
            resources:
              requests:
                memory: "128Mi"  # 提高内存请求和限制，适应生产负载
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "1"
          restartPolicy: OnFailure  # 仅在任务失败时重试